# Generated by Django 4.2 on 2024-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='asset',
            field=models.CharField(choices=[('BTCUSDT', 'BTCUSDT'), ('ETHUSDT', 'ETHUSDT')], default='BTCUSDT', max_length=15),
            preserve_default=False,
        ),
    ]
