# Generated by Django 4.2 on 2024-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_triggered',
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('DELETED', 'DELETED'), ('TRIGGERED', 'TRIGGERED')], default='CREATED', max_length=10),
            preserve_default=False,
        ),
    ]
