# Generated by Django 4.2 on 2024-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_alert_is_triggered_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('DELETED', 'DELETED'), ('TRIGGERED', 'TRIGGERED')], default='CREATED', max_length=10),
        ),
    ]
